FROM python:3.10.5-slim-buster
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY Pipfile .
COPY Pipfile.lock .
COPY ./src /app

RUN groupadd credentials_manager
RUN useradd -g credentials_manager credentials_manager
RUN chown -R credentials_manager:credentials_manager /app

RUN pip install --upgrade pip

RUN apt-get update && apt-get install -y git gcc python3-dev musl-dev libpq-dev

RUN pip install pipenv && pipenv install --system
