version: '3'

services:
  web:
    container_name: am_web
    build:
      context: .
    command: python -m gunicorn --workers=4 --env DJANGO_SETTINGS_MODULE=conf.settings conf.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    environment:
      SERVICE: "web"
    ports:
      - ${WEB_PORT}:8000
    volumes:
      - ./src:/app
    depends_on:
      - db
      - amqp
    networks:
      - am_network
    restart: always

  celery:
    container_name: am_celery
    build:
      context: .
    command: python -m celery -A conf.celery worker -l INFO --beat --uid account_manager -c 4 -s /tmp/celerybeat-schedule.db
    env_file:
      - .env
    environment:
      SERVICE: "celery"
    volumes:
      - ./src:/app
    depends_on:
      - db
      - amqp
    networks:
      - am_network
    restart: always

  db:
    container_name: am_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - '../db/account_manager:/var/lib/postgresql/data'
    networks:
      - am_network
    restart: always

  amqp:
    image: rabbitmq:3.10.6-management-alpine
    container_name: am_amqp
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - am_network
    restart: always

  filebeat:
    image: elastic/filebeat:7.16.2
    container_name: am_filebeat
    volumes:
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./src/logs:/logs:ro
    networks:
      - elk_network
    env_file:
      - .env
    restart: always

networks:
  am_network:
    name: am_network
    driver: bridge

  elk_network:
    external: true