version: '3'

services:
  web:
    container_name: credentials_manager_server
    build:
      dockerfile: Dockerfile.web
      context: ./
    command: uwsgi --ini /config/uwsgi.ini
    env_file:
      - .env.docker
    environment:
      - REDIS_HOST=redis
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ./src:/app
    depends_on:
      - db
      - redis
    restart: on-failure

  db:
    container_name: credentials_manager_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=credentials_manager
      - POSTGRES_USER=credentials_manager
      - POSTGRES_PASSWORD=credentials_manager
    ports:
      - 25432:5432
    volumes:
      - '../db/credentials_manager:/var/lib/postgresql/data'
    restart: always

  celery:
    build:
      dockerfile: Dockerfile.celery
      context: ./
    command: python -m celery -A conf.celery worker -l INFO --beat --uid credentials_manager -c 2
    env_file:
      - .env.docker
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./src:/app
    depends_on:
      - db
      - redis
    restart: on-failure

  redis:
    image: "redis:latest"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 26379:6379
