# Generated by Django 4.0.5 on 2022-06-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('facebook', 'Facebook'), ('vk', 'Vk')], max_length=255)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'аккаунт',
                'verbose_name_plural': 'аккаунты',
            },
        ),
        migrations.CreateModel(
            name='CredentialsProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('approval_needed', 'Approval Needed'), ('temporary_banned', 'Temporary Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], max_length=255)),
                ('status_updated', models.DateTimeField(auto_now=True)),
                ('waiting_delta', models.IntegerField(default=0, help_text='In minutes')),
                ('enable', models.BooleanField(default=True)),
                ('start_time_of_use', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'прокси-аккаунт',
                'verbose_name_plural': 'прокси-аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, unique=True)),
                ('port', models.CharField(max_length=255)),
                ('login', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('ip_not_equal', 'Ip Not Equal')], max_length=255)),
                ('status_updated', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'прокси',
                'verbose_name_plural': 'прокси',
            },
        ),
        migrations.AddConstraint(
            model_name='proxy',
            constraint=models.UniqueConstraint(fields=('ip', 'port'), name='ip_port_constraint'),
        ),
        migrations.AddField(
            model_name='credentialsproxy',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.credentials'),
        ),
        migrations.AddField(
            model_name='credentialsproxy',
            name='proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.proxy'),
        ),
        migrations.AddConstraint(
            model_name='credentialsproxy',
            constraint=models.UniqueConstraint(fields=('credentials', 'proxy'), name='credentials_proxy_constraint'),
        ),
    ]
