# Generated by Django 4.0.5 on 2022-06-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsproxy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('approval_needed', 'Approval Needed'), ('temporary_banned', 'Temporary Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], default='available', max_length=255),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('ip_not_equal', 'Ip Not Equal')], default='available', max_length=255),
        ),
    ]
