# Generated by Django 4.0.5 on 2022-06-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_credentialsproxy_status_alter_proxy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='login',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='credentials',
            constraint=models.UniqueConstraint(fields=('network', 'login'), name='network_login_constraint'),
        ),
    ]
