# Generated by Django 4.0.5 on 2022-06-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_credentials_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsproxy',
            name='status_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsproxy',
            name='credentials',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.credentials'),
        ),
        migrations.AlterField(
            model_name='credentialsproxy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('login_failed', 'Login Failed'), ('temporary_banned', 'Temporary Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], default='available', max_length=255),
        ),
    ]
