# Generated by Django 4.0.5 on 2022-07-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_credentialsproxy_status_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('limit', models.IntegerField()),
            ],
            options={
                'verbose_name': 'сеть',
                'verbose_name_plural': 'сети',
            },
        ),
        migrations.AlterField(
            model_name='credentialsproxy',
            name='start_time_of_use',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsproxy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('not_available', 'Not Available'), ('login_failed', 'Login Failed'), ('temporarily_banned', 'Temporarily Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], default='available', max_length=255),
        ),
    ]
