# Generated by Django 4.0.5 on 2022-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_network_alter_credentialsproxy_start_time_of_use_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='credentials',
            name='network_login_constraint',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='network',
        ),
    ]
