# Generated by Django 4.0.5 on 2022-07-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_credentials_network_login_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.network'),
        ),
        migrations.AddConstraint(
            model_name='credentials',
            constraint=models.UniqueConstraint(fields=('network', 'login'), name='network_login_constraint'),
        ),
    ]
