# Generated by Django 4.0.5 on 2022-07-16 05:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_credentials_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsproxy',
            name='cookies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credentialsproxy',
            name='time_of_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsproxy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sent', 'Sent'), ('used', 'Used'), ('not_available', 'Not Available'), ('login_failed', 'Login Failed'), ('temporarily_banned', 'Temporarily Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], default='available', max_length=255),
        ),
        migrations.AlterField(
            model_name='credentialsproxy',
            name='waiting_delta',
            field=models.IntegerField(default=3600, help_text='In seconds'),
        ),
        migrations.CreateModel(
            name='CredentialsStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_title', models.CharField(max_length=255)),
                ('start_time_of_use', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time_of_use', models.DateTimeField()),
                ('request_count', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('result_status', models.CharField(choices=[('temporarily_banned', 'Temporarily Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], max_length=255)),
                ('status_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('credentials_proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.credentialsproxy')),
            ],
            options={
                'verbose_name': 'статистика по аккаунтам',
                'verbose_name_plural': 'статистика по аккаунтам',
            },
        ),
    ]
