# Generated by Django 4.0.5 on 2022-07-18 06:12

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_credentialsproxy_cookies_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='credentialsproxy',
            managers=[
                ('objects', core.models.CredentialsProxyManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='network',
            name='limit',
        ),
        migrations.AlterField(
            model_name='credentialsstatistics',
            name='result_status',
            field=models.CharField(choices=[('not_available', 'Not Available'), ('login_failed', 'Login Failed'), ('temporarily_banned', 'Temporarily Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], max_length=255),
        ),
        migrations.AlterField(
            model_name='credentialsstatistics',
            name='start_time_of_use',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ParsingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('limit', models.IntegerField(default=0)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='core.network')),
            ],
        ),
    ]
