# Generated by Django 4.0.5 on 2022-07-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_credentialsproxy_managers_remove_network_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsingtype',
            options={'verbose_name': 'Ограничения на типы парсинга', 'verbose_name_plural': 'Ограничения на типы парсинга'},
        ),
        migrations.AddField(
            model_name='parsingtype',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
