# Generated by Django 4.0.5 on 2022-07-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_parsingtype_options_parsingtype_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsingtype',
            options={'verbose_name': 'ограничение на типы парсинга', 'verbose_name_plural': 'ограничения на типы парсинга'},
        ),
        migrations.RemoveField(
            model_name='credentialsstatistics',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='credentialsstatistics',
            name='request_count',
        ),
    ]
