# Generated by Django 4.0.5 on 2022-07-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_parsingtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsstatistics',
            name='limit',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='credentialsstatistics',
            name='request_count',
            field=models.JSONField(null=True),
        ),
    ]
