# Generated by Django 4.0.5 on 2022-07-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_credentialsstatistics_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsproxy',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
