# Generated by Django 4.0.6 on 2022-07-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_credentialsproxy_counter'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='credentialsproxy',
            name='credentials_proxy_constraint',
        ),
        migrations.AlterField(
            model_name='credentialsstatistics',
            name='credentials_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to='core.credentialsproxy'),
        ),
    ]
