# Generated by Django 4.0.6 on 2022-07-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_credentialsproxy_credentials_proxy_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsproxy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_queue', 'In Queue'), ('sent', 'Sent'), ('used', 'Used'), ('not_available', 'Not Available'), ('login_failed', 'Login Failed'), ('temporarily_banned', 'Temporarily Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], default='available', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='credentialsproxy',
            constraint=models.UniqueConstraint(fields=('credentials', 'proxy'), name='credentials_proxy_constraint'),
        ),
    ]
