# Generated by Django 4.1 on 2022-08-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_credentialsproxy_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='dynamic_limits',
            field=models.BooleanField(default=False),
        ),
    ]
