# Generated by Django 4.1.1 on 2022-10-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_network_dynamic_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsproxy',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='type',
            field=models.CharField(choices=[('socks5', 'Socks5'), ('http', 'Http')], default='http', max_length=255),
        ),
    ]
