# Generated by Django 4.1.1 on 2022-10-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_credentialsproxy_token_proxy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='ip',
            field=models.CharField(max_length=255),
        ),
    ]
