# Generated by Django 4.1.2 on 2022-10-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_proxy_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='mobile',
            field=models.BooleanField(default=False),
        ),
    ]
