# Generated by Django 4.1.2 on 2022-10-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_proxy_expiration_date_proxy_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.network')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='core.proxy')),
            ],
        ),
    ]
