# Generated by Django 4.1.2 on 2022-10-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_proxycounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsstatistics',
            name='status_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
