# Generated by Django 4.1.2 on 2022-11-17 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_credentialsstatistics_status_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsproxy',
            name='proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credentials_proxy', to='core.proxy'),
        ),
        migrations.AlterField(
            model_name='credentialsproxy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_queue', 'In Queue'), ('sent', 'Sent'), ('not_available', 'Not Available'), ('login_failed', 'Login Failed'), ('temporarily_banned', 'Temporarily Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], default='available', max_length=255),
        ),
    ]
