# Generated by Django 4.1.2 on 2022-11-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_credentialsproxy_proxy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsproxy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_queue', 'In Queue'), ('sent', 'Sent'), ('not_available', 'Not Available'), ('proxy_error', 'Proxy Error'), ('login_failed', 'Login Failed'), ('temporarily_banned', 'Temporarily Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], default='available', max_length=255),
        ),
    ]
