# Generated by Django 4.1.2 on 2022-12-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_credentialsproxy_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxycounter',
            options={'verbose_name': 'счетчик прокси', 'verbose_name_plural': 'счетчик прокси'},
        ),
        migrations.AddConstraint(
            model_name='proxycounter',
            constraint=models.UniqueConstraint(fields=('network', 'proxy'), name='network_proxy_constraint'),
        ),
    ]
