# Generated by Django 4.1.2 on 2022-12-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_proxycounter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsstatistics',
            name='account_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
