# Generated by Django 4.1.2 on 2022-12-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_credentialsstatistics_account_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='today_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxy',
            name='tomorrow_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
