# Generated by Django 4.1.2 on 2022-12-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_credentials_price_proxy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsstatistics',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to='core.proxy'),
        ),
    ]
