# Generated by Django 4.1.2 on 2022-12-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_credentialsstatistics_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='price',
        ),
        migrations.CreateModel(
            name='ProxyRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='core.proxy')),
            ],
            options={
                'verbose_name': 'аренда прокси',
                'verbose_name_plural': 'аренда прокси',
            },
        ),
    ]
