# Generated by Django 4.1.2 on 2022-12-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_proxy_expiration_date_remove_proxy_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='today_notification',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='tomorrow_notification',
        ),
        migrations.AddField(
            model_name='proxyrent',
            name='today_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxyrent',
            name='tomorrow_notification',
            field=models.BooleanField(default=False),
        ),
    ]
