# Generated by Django 4.1.2 on 2022-12-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_proxy_today_notification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsingtype',
            options={'verbose_name': 'Типы парсинга', 'verbose_name_plural': 'Типы парсинга'},
        ),
        migrations.AddField(
            model_name='credentials',
            name='cookies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='core.proxy'),
        ),
        migrations.AddField(
            model_name='credentials',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_queue', 'In Queue'), ('sent', 'Sent'), ('invalid', 'Invalid'), ('not_available', 'Not Available'), ('proxy_error', 'Proxy Error'), ('login_failed', 'Login Failed'), ('temporarily_banned', 'Temporarily Banned'), ('waiting', 'Waiting')], default='available', max_length=255),
        ),
        migrations.AddField(
            model_name='credentials',
            name='status_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='status_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='time_of_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='waiting_delta',
            field=models.IntegerField(default=3600, help_text='In seconds'),
        ),
        migrations.AddField(
            model_name='network',
            name='need_proxy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='login',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsstatistics',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proxy'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='type',
            field=models.CharField(choices=[('socks5', 'Socks5'), ('http', 'Http'), ('https', 'Https')], default='http', max_length=255),
        ),
        migrations.CreateModel(
            name='AccountStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_of_use', models.DateTimeField()),
                ('end_time_of_use', models.DateTimeField()),
                ('request_count', models.JSONField(null=True)),
                ('limit', models.JSONField(null=True)),
                ('result_status', models.CharField(choices=[('not_available', 'Not Available'), ('login_failed', 'Login Failed'), ('temporarily_banned', 'Temporarily Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], max_length=255)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.credentials')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to='core.proxy')),
            ],
            options={
                'verbose_name': 'статистика по аккаунтам',
                'verbose_name_plural': 'статистика по аккаунтам',
            },
        ),
    ]
