# Generated by Django 4.1.4 on 2022-12-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_parsingtype_options_credentials_cookies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('market', models.CharField(default='unknown', max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_queue', 'In Queue'), ('sent', 'Sent'), ('invalid', 'Invalid'), ('not_available', 'Not Available'), ('proxy_error', 'Proxy Error'), ('login_failed', 'Login Failed'), ('temporarily_banned', 'Temporarily Banned'), ('waiting', 'Waiting')], default='available', max_length=255)),
                ('status_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('status_updated', models.DateTimeField(auto_now=True)),
                ('waiting_delta', models.IntegerField(default=3600, help_text='In seconds')),
                ('time_of_sent', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('cookies', models.JSONField(blank=True, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('enable', models.BooleanField(default=True)),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.network')),
            ],
            options={
                'verbose_name': 'аккаунт',
                'verbose_name_plural': 'аккаунты',
            },
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='network',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='proxy',
        ),
        migrations.RemoveField(
            model_name='credentialsstatistics',
            name='credentials_proxy',
        ),
        migrations.RemoveField(
            model_name='credentialsstatistics',
            name='proxy',
        ),
        migrations.AddField(
            model_name='proxy',
            name='market',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.DeleteModel(
            name='CredentialsProxy',
        ),
        migrations.DeleteModel(
            name='CredentialsStatistics',
        ),
        migrations.AddField(
            model_name='account',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='core.proxy'),
        ),
        migrations.AlterField(
            model_name='accountstatistics',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.account'),
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('network', 'login'), name='network_login_constraint'),
        ),
    ]
