# Generated by Django 4.1.4 on 2022-12-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_account_remove_credentials_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyrent',
            name='five_day_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_queue', 'In Queue'), ('sent', 'Sent'), ('invalid', 'Invalid'), ('not_available', 'Not Available'), ('proxy_error', 'Proxy Error'), ('login_failed', 'Login Failed'), ('temporarily_banned', 'Temporarily Banned'), ('banned', 'Banned'), ('waiting', 'Waiting')], default='available', max_length=255),
        ),
    ]
