# Generated by Django 4.1.4 on 2022-12-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_proxyrent_five_day_notification_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='market',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='market',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
    ]
