# Generated by Django 4.1.4 on 2022-12-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_account_market_alter_proxy_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.network'),
        ),
        migrations.AlterField(
            model_name='account',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='core.proxy'),
        ),
        migrations.AlterField(
            model_name='accountstatistics',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statistics', to='core.proxy'),
        ),
        migrations.AlterField(
            model_name='proxycounter',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.network'),
        ),
        migrations.AlterField(
            model_name='proxycounter',
            name='proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='core.proxy'),
        ),
        migrations.AlterField(
            model_name='proxyrent',
            name='proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rents', to='core.proxy'),
        ),
    ]
