# Generated by Django 4.1.4 on 2022-12-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_account_network_alter_account_proxy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountstatistics',
            old_name='limit',
            new_name='limits',
        ),
    ]
