# Generated by Django 4.1.4 on 2022-12-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_limit_accountstatistics_limits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountstatistics',
            old_name='start_time_of_use',
            new_name='time_of_sent',
        ),
    ]
